// Brami3D — módulo i18n (ES/EN) de brami3d_supabase.html.
// Script clásico SIN build: define LANG, I18N, t(), applyStaticI18n(),
// setLang()/toggleLang() como globales. Debe cargarse ANTES del script
// principal (que los usa). Las funciones que referencia del principal
// ($ , buildNav, render, …) solo se llaman en runtime.

// ═══════════════════════════════════════════════
//  I18N — español (por defecto) / inglés
// ═══════════════════════════════════════════════
// Por defecto español; el inglés es opt-in con el selector. Lo no traducido cae a
// español. El módulo fiscal (SIF/AEAT) se oculta en inglés (es específico de España).
let LANG = (localStorage.getItem('b3d_lang')==='en') ? 'en' : 'es';
const I18N = {
  es: {
    'nav.dashboard':'Dashboard','nav.agenda':'Agenda','nav.clientes':'Clientes',
    'agenda.title':'Agenda','agenda.overdue':'Atrasados','agenda.todayTitle':'Para hoy','agenda.today':'Hoy','agenda.week':'Esta semana','agenda.noDate':'Sin fecha de entrega','agenda.empty':'No tienes entregas pendientes. ¡Todo al día! 🎉','agenda.late':'hace {n} día(s)','agenda.in':'en {n} día(s)','agenda.toCollect':'Pendiente de cobro','agenda.later':'Más adelante','agenda.deliver':'Marcar entregado','agenda.collect':'Cobrar','nav.pedidos':'Pedidos','nav.impresoras':'Impresoras',
    'nav.filamentos':'Filamentos','nav.piezas':'Piezas','nav.cobros':'Cobros','nav.archivos':'Archivos',
    'nav.gastos':'Gastos','nav.registro':'Registro fiscal','nav.calculadora':'Calculadora','nav.configuracion':'Configuración','nav.admin':'Admin',
    'nav.grp.ventas':'Ventas','nav.grp.taller':'Taller','nav.grp.finanzas':'Finanzas',
    'common.logout':'Cerrar sesión','common.menu':'Menú','common.cancel':'Cancelar','common.save':'Guardar','common.new':'+ Nuevo','common.delete':'Eliminar',
    'common.day':'día','common.days':'días','common.prev':'← Anterior','common.next':'Siguiente →',
    'topbar.searchDesk':'Buscar clientes, pedidos, piezas…','net.offline':'Sin conexión','net.unsynced':'sin sincronizar',
    'theme.toggle':'Cambiar tema','lang.toggle':'Cambiar idioma (ES/EN)',
    'col.num':'Nº','col.project':'Proyecto','col.material':'Material','col.price':'Precio','col.status':'Estado','col.date':'Fecha',
    'dash.title':'Dashboard','dash.subtitle':'Resumen de tu negocio','dash.monthlyReport':'Informe mensual','dash.annualReport':'Informe anual',
    'dash.incomeCollected':'Ingresos cobrados','dash.paidOrders':'pedidos pagados','dash.prodCosts':'Costes producción',
    'dash.totalExpenses':'Gastos totales','dash.expenses':'gastos','dash.netProfit':'Beneficio neto','dash.marginOk':'Margen positivo ✓','dash.checkPrices':'Revisar precios',
    'dash.totalOrders':'Total pedidos','dash.pending':'pendientes','dash.printing':'imprimiendo',
    'dash.incomeByMonth':'Ingresos por mes','dash.byStatus':'Por estado','dash.tapToFilter':'— toca para filtrar','dash.topMaterials':'Materiales más usados',
    'dash.recentOrders':'Últimos pedidos','dash.noOrdersYet':'Sin pedidos aún','dash.noOrders':'Sin pedidos',
    'dash.lowFilament':'Stock bajo de filamento','dash.gLeft':'g restantes','dash.restock':'Reponer',
    'dash.pendingCollect':'Pendiente de cobrar','dash.finishedUnpaid':'pedidos sin cobrar','dash.collect':'Cobrar',
    'dash.staleOrders':'Pedidos sin actualizar','dash.staleSub':'Llevan más de 3 días en el mismo estado','dash.update':'Actualizar',
    'an.title':'Análisis','an.avgTicket':'Ticket medio','an.avgTicketSub':'por pedido cobrado','an.conversion':'Tasa de conversión','an.conversionSub':'presupuestos cobrados','an.grossProfit':'Beneficio bruto','an.grossMargin':'margen','an.profitByClient':'Rentabilidad por cliente','an.profitByMaterial':'Rentabilidad por material','an.colProfit':'Beneficio','an.colIncome':'Ingresos','an.colOrders':'Pedidos','an.colMargin':'Margen','an.noData':'Aún no hay pedidos cobrados','an.client':'Cliente','an.material':'Material',
    'st.todos':'todos','st.pendiente':'pendiente','st.imprimiendo':'imprimiendo','st.terminado':'terminado','st.entregado':'entregado','st.cobrado':'cobrado','st.pagado':'pagado','st.activa':'activa','st.mantenimiento':'mantenimiento','st.averiada':'averiada',
    'common.exportExcel':'Exportar Excel','common.page':'Página','common.of':'de','common.search':'Buscar…',
    'ped.title':'Pedidos','ped.ordersWord':'pedidos','ped.inTotal':'en total','ped.searchProject':'Buscar proyecto, cliente, nº factura…',
    'ped.selectedWord':'seleccionados','ped.changeStatusTo':'→ Cambiar estado a:','ped.deselect':'✕ Deseleccionar',
    'ped.empty':'Sin pedidos — crea tu primer pedido 👆','ped.selectAll':'Seleccionar página','ped.deselectAll':'Deseleccionar todo',
    'col.client':'Cliente','col.weight':'Peso','col.numInvoice':'Nº / Factura',
    'ped.tPresupuesto':'Presupuesto PDF','ped.tWhatsApp':'WhatsApp','ped.tCobrado':'Marcar como cobrado','ped.tYaCobrado':'Ya cobrado',
    'ped.tVerFactura':'Ver factura PDF','ped.tGenFactura':'Generar factura','ped.tEnviarFactura':'Enviar factura por WhatsApp',
    'ped.tDuplicar':'Duplicar pedido','ped.tSoloPagados':'Solo para pedidos pagados','ped.types':'tipos','ped.units':'uds',
    'ped.overdue':'vencido','ped.delivery':'entrega','ped.paidBadge':'cobrado','ped.deposit':'Anticipo','ped.balance':'pendiente',
    'share.title':'Compartir presupuesto','share.linkReady':'Enlace de aceptación listo. Cópialo o envíalo al cliente — podrá verlo y aceptarlo online:','share.copy':'📋 Copiar enlace','share.copied':'Enlace copiado','share.openWa':'💬 Enviar por WhatsApp','share.waMsg':'¡Hola! Aquí tienes tu presupuesto para "{p}". Puedes verlo y aceptarlo aquí: {url}','share.needSql':'Función no disponible todavía: ejecuta la migración sql/010 en Supabase.','share.accepted':'Aceptado','share.tShare':'Compartir enlace de aceptación',
    'plan.limitTitle':'Límite del plan alcanzado','plan.proMonthly':'💳 Pro Mensual — 9€/mes','plan.proAnnual':'💳 Pro Anual — 79€/año','plan.payPaypal':'Pagar con PayPal','plan.notNow':'Ahora no','plan.redirecting':'Abriendo pago seguro…','plan.checkoutErr':'No se pudo iniciar el pago','plan.thanks':'✅ ¡Pago recibido! Activando tu plan Pro…',
    'email.title':'Enviar por email','email.recipient':'Email del destinatario:','email.testNote':'El correo se enviará desde tu dominio (brami3d.app) con el nombre de tu empresa; las respuestas llegarán a tu email de contacto.','email.send':'Enviar','email.invalidTo':'Introduce un email válido','email.sent':'✅ Email enviado','email.errPrefix':'No se pudo enviar','email.hi':'Hola','email.regards':'Un saludo,','email.subjQuote':'Presupuesto {n}','email.subjInvoice':'Factura {n}','email.quoteIntro':'Te envío el presupuesto para "{p}".','email.invoiceIntro':'Adjunto la factura {n} correspondiente a "{p}".','email.priceLine':'Precio total: {v}.','email.totalLine':'Total: {v}.','email.subjReminder':'Recordatorio — Presupuesto {n}','email.reminderIntro':'Hace unos días te envié el presupuesto para "{p}" y no quería que se te pasara. Te lo adjunto de nuevo.','email.reminderLink':'Puedes verlo y aceptarlo online aquí: {url}','ped.tRecordar':'Recordar presupuesto al cliente',
    'frm.editOrder':'Editar pedido','frm.newOrder':'Nuevo pedido','frm.saveOrder':'💾 Guardar pedido','frm.noClient':'Sin cliente',
    'frm.projectName':'Nombre del proyecto *','frm.orderDate':'Fecha pedido','frm.deliveryDate':'Fecha de entrega (opcional)',
    'frm.printer':'Impresora','frm.noPrinter':'Sin impresora (200W por defecto)',
    'frm.designCost':'Coste diseño (€)','frm.postCost':'Coste postprocesado (€)',
    'frm.manualProfit':'Ganancia manual (€) — vacío = margen automático','frm.salePrice':'Precio de venta (€) — sobreescribe todo (0 = gratis / pérdida)',
    'frm.deposit':'Anticipo / señal cobrada (€)','frm.orderPaid':'💰 Pedido cobrado','frm.markPaid':'💰 Marcar como cobrado',
    'frm.paidOn':'Cobrado el {d}','frm.willInvoice':'Al marcar como cobrado se generará la factura','frm.notes':'Notas',
    'frm.refPhoto':'📷 Foto de referencia','frm.addPhoto':'Añadir foto de referencia','frm.photoHint':'JPG, PNG, WebP — máx. 10MB',
    'frm.orderParts':'Piezas del pedido','frm.partsHint':'Cada pieza se imprime por separado.','frm.addPart':'+ Añadir pieza',
    'frm.totalWeight':'Peso total','frm.totalTime':'Tiempo total','frm.parts':'Piezas','frm.costPreview':'Vista previa de costes',
    'ln.noTemplate':'── Sin plantilla ──','ln.manual':'── Manual ──','ln.weightG':'Peso (g):','ln.part':'Pieza','ln.remove':'✕ Quitar',
    'ln.template':'Plantilla','ln.descRequired':'Descripción *','ln.descPlaceholder':'Ej: Soporte lateral','ln.qty':'Cantidad','ln.unitTime':'Tiempo unitario (h)',
    'ln.filaments':'🧵 Filamentos de esta pieza','ln.addFilament':'+ Añadir filamento','ln.partWeight':'Peso total pieza:',
    'cp.filamentCost':'Coste filamentos','cp.electricity':'Electricidad','cp.postproc':'Postprocesado','cp.design':'Diseño','cp.totalCost':'Coste total','cp.profit':'Beneficio','cp.finalPrice':'PRECIO FINAL',
    'save.projectRequired':'Proyecto obligatorio','save.addPart':'Añade al menos una pieza','save.saved':'✅ Pedido guardado','save.savedOk':'Pedido guardado correctamente',
    'save.sendQuoteTo':'¿Envías el presupuesto a','save.sendWhatsApp':'💬 Enviar por WhatsApp','save.notNow':'Ahora no','save.bulkUpdated':'pedidos actualizados a',
    'col.name':'Nombre','col.empresa':'Empresa','col.phone':'Teléfono','col.email':'Email','col.notes':'Notas','col.nif':'NIF/CIF',
    'cli.title':'Clientes','cli.clientsWord':'clientes','cli.empty':'Sin clientes','cli.purchaseHistory':'📋 Historial de compras','cli.tHistory':'Historial',
    'cli.editClient':'Editar cliente','cli.newClient':'Nuevo cliente','cli.nameRequired':'Nombre *','cli.address':'Dirección',
    'cli.saved':'Cliente guardado','cli.nameReq':'Nombre obligatorio','cli.deleteConfirm':'¿Eliminar este cliente?','cli.importCsv':'📥 Importar CSV',
    'common.close':'Cerrar','hist.noOrders':'Sin pedidos registrados','hist.orders':'Pedidos','hist.paid':'Pagados','hist.totalCollected':'Total cobrado',
    'common.edit':'Editar','common.saved':'Guardado','common.deleted':'Eliminado','common.nameReq':'Nombre obligatorio',
    'a11y.delete':'Eliminar','a11y.remove':'Quitar','a11y.search':'Buscar','a11y.lang':'Cambiar idioma','a11y.theme':'Cambiar tema',
    'onb.title':'¡Bienvenido a Brami3D! 👋','onb.intro':'En 3 pasos tienes tu taller listo para funcionar.','onb.doneTag':'✓ Hecho','onb.skip':'Explorar por mi cuenta',
    'onb.s1t':'Configura tu empresa','onb.s1d':'Nombre, logo e impuestos para tus facturas.','onb.s1b':'Configurar',
    'onb.s2t':'Añade tu primer filamento','onb.s2d':'Registra una bobina con su precio y stock.','onb.s2b':'Añadir filamento',
    'onb.s3t':'Crea tu primer pedido','onb.s3d':'Calcula el precio y genera el presupuesto o la factura.','onb.s3b':'Crear pedido',
    'err.generic':'Algo falló. Inténtalo de nuevo.',
    'trial.daysLeft':'Te quedan {n} días de prueba gratis.','trial.lastDay':'Hoy es el último día de tu prueba gratis.','trial.upgrade':'Pásate a Pro',
    'cfg.notifTest':'📲 Enviar notificación de prueba','push.testBody':'¡Funciona! Tus notificaciones están activas.','push.testSent':'✅ Notificación enviada — míra tu dispositivo','push.testNone':'No hay dispositivos suscritos todavía',
    'cfg.dangerZone':'Zona de peligro','cfg.deleteAccount':'Eliminar mi cuenta','cfg.deleteAccountHint':'Borra permanentemente tu cuenta y todos tus datos (pedidos, clientes, facturas…). No se puede deshacer.',
    'del.title':'Eliminar cuenta','del.warn':'Esto borrará para siempre tu cuenta y TODOS tus datos: pedidos, clientes, filamentos, facturas y configuración. Esta acción no se puede deshacer.','del.confirmHint':'Para confirmar, escribe ELIMINAR:','del.confirmWord':'ELIMINAR','del.confirmBtn':'Eliminar todo','del.done':'Tu cuenta y tus datos se han eliminado.','del.error':'No se pudo eliminar la cuenta',
    'help.btn':'Ayuda','help.title':'Ayuda y contacto','help.intro':'Dudas rápidas — y si no, escríbenos, respondemos en menos de 24 h.',
    'help.q1':'¿Cómo creo una factura?','help.a1':'Marca el pedido como cobrado y se genera la factura legal automáticamente. La ves o la compartes en PDF desde el propio pedido.',
    'help.q2':'¿Cómo paso a Pro?','help.a2':'Toca tu plan arriba (la etiqueta junto a tu nombre) y elige Pro mensual o anual. El pago con tarjeta lo activa al instante.',
    'help.q3':'¿Mis datos están seguros?','help.a3':'Sí. Se guardan cifrados en la nube y solo tú accedes a ellos. Puedes exportarlos o eliminar tu cuenta cuando quieras.',
    'help.wa':'Escríbenos por WhatsApp','help.email':'Escríbenos un email','help.waMsg':'Hola, necesito ayuda con Brami3D',
    'cfg.referrals':'🤝 Invita y gana','cfg.referralsHint':'Invita a otro taller. Cuando se registre con tu enlace, os lleváis los dos 30 días de Pro gratis.','cfg.referralsBtn':'Ver mi enlace de invitación',
    'ref.title':'Invita y gana','ref.intro':'Comparte tu enlace. Cuando otro taller se registre con él, ambos conseguís 30 días de Pro gratis. 🎁','ref.copy':'Copiar','ref.copied':'Enlace copiado','ref.share':'Compartir por WhatsApp','ref.count':'Talleres que has invitado','ref.waMsg':'Te recomiendo Brami3D para gestionar tu taller de impresión 3D. Regístrate con mi enlace y los dos nos llevamos 30 días Pro gratis: {url}','ref.rewarded':'🎁 ¡Bienvenido! Tienes 30 días de Pro gratis por venir invitado.',
    'imp.title':'Impresoras','imp.new':'+ Nueva impresora','imp.empty':'Sin impresoras','imp.wear':'Desgaste','imp.needsReview':'requiere revisión','imp.elecCost':'Coste eléctrico','imp.regUse':'⏱ Registrar uso','imp.editTitle':'Editar impresora','imp.newTitle':'Nueva impresora','imp.fModel':'Modelo','imp.fHours':'Horas de uso','imp.fWear':'% Desgaste','imp.fConsumo':'Consumo eléctrico (W)','imp.consumoHint':'Introduce los vatios de tu impresora','imp.delete':'¿Eliminar esta impresora?','imp.logUsage':'⏱ Registrar uso','imp.accNow':'Acumulado actual:','imp.wearWord':'Desgaste:','imp.estElecCost':'Coste eléctrico estimado:','imp.sessHours':'Horas de esta sesión *','imp.extraWear':'Desgaste adicional (%)','imp.wearAuto':'Si dejas el desgaste en 0 se aplica +0.1% por hora automáticamente.','imp.fMantCada':'Mantenimiento cada (h)','imp.maint':'Mantenimiento','imp.maintDue':'Toca mantenimiento','imp.mantBtn':'Mantenimiento hecho','imp.mantDone':'Mantenimiento registrado ✅',
    'fil.title':'Filamentos','fil.empty':'Sin filamentos','fil.cRemaining':'Restante','fil.cStock':'Stock','fil.editTitle':'Editar filamento','fil.newTitle':'Nuevo filamento','fil.fType':'Tipo','fil.fBrand':'Marca *','fil.fColor':'Color','fil.fRemaining':'Peso restante (g)','fil.fPriceKg':'Precio por kg (€)','fil.brandReq':'Marca obligatoria','fil.delete':'¿Eliminar este filamento?','fil.cType':'Tipo','fil.cBrand':'Marca','fil.cColor':'Color',
    'pz.title':'Piezas','pz.new':'+ Nueva pieza','pz.empty':'Sin piezas guardadas','pz.hint':'Guarda piezas frecuentes para auto-rellenar pedidos.','pz.material':'Material','pz.weight':'Peso','pz.time':'Tiempo','pz.suggested':'Sugerido','pz.editTitle':'Editar pieza','pz.newTitle':'Nueva pieza','pz.fName':'Nombre *','pz.fMaterial':'Material','pz.fWeight':'Peso (g)','pz.fTime':'Tiempo impresión (h)','pz.fSuggested':'Precio sugerido (€)','pz.delete':'¿Eliminar esta pieza?',
    'gas.title':'Gastos','gas.subtitle':'Control de todos tus gastos','gas.new':'+ Nuevo gasto','gas.empty':'Sin gastos registrados','gas.total':'Total gastos','gas.registered':'gastos registrados','gas.thisMonth':'Este mes','gas.byCat':'Por categoría','gas.noData':'Sin datos','gas.editTitle':'Editar gasto','gas.newTitle':'Nuevo gasto','gas.fDesc':'Descripción *','gas.fCat':'Categoría','gas.fAmount':'Importe (€)','gas.fDate':'Fecha','gas.fSupplier':'Proveedor','gas.descReq':'Descripción obligatoria','gas.saved':'Gasto guardado','gas.delete':'¿Eliminar este gasto?',
    'arch.title':'Archivos','arch.hint':'STL e imágenes — guardados en Supabase Storage (máx. 50MB).','arch.drop':'Arrastra archivos o haz clic','arch.dropHint':'STL · JPG · PNG · WebP · GIF · SVG · Máx. 50MB','arch.empty':'Sin archivos',
    'cob.title':'Cobros pendientes','cob.toCollect':'por cobrar','calc.title':'🧮 Calculadora rápida','calc.subtitle':'Estima coste y precio sin crear un pedido','calc.printParams':'Parámetros de impresión','calc.filament':'Filamento','calc.filManual':'── Coste manual (€/kg) ──','calc.filCost':'Coste filamento (€/kg)','calc.weightG':'Peso (g)','calc.printTime':'Tiempo impresión (h)','calc.printer':'Impresora','calc.noPrinter':'── Sin impresora (200W) ──','calc.postproc':'Postprocesado','calc.design':'Diseño / modeling','calc.margin':'Margen de beneficio (%)','calc.manualPrice':'Precio final manual','calc.manualPriceHint':'— deja vacío para calcular automático','calc.optional':'Opcional','calc.enterData':'Introduce los datos para ver el desglose','calc.breakdown':'Desglose de costes','calc.cMaterial':'Material','calc.cElectricity':'Electricidad','calc.cPostproc':'Postprocesado','calc.cDesign':'Diseño','calc.cTotalCost':'Coste total','calc.manualPriceLbl':'Precio manual','calc.suggestedPrice':'Precio sugerido','calc.marginWord':'margen','calc.profit':'Beneficio','calc.priceByMargin':'Tabla de precios por margen','calc.colMargin':'Margen','calc.colPrice':'Precio','calc.colProfit':'Beneficio',
    'toast.connRestored':'✅ Conexión restaurada','toast.offline':'⚠️ Sin conexión — modo offline','toast.notifNotSupported':'Tu navegador no soporta notificaciones','toast.notifOn':'Notificaciones activadas','toast.permDenied':'Permiso denegado','toast.photoTooBig':'La foto supera 10MB','toast.logoFormat':'Formato no válido. Usa PNG, JPG, WebP o SVG.','toast.notesSaved':'Notas guardadas','toast.planUpdated':'Plan actualizado','toast.csvInvalid':'CSV no válido','toast.csvEmpty':'El CSV está vacío','toast.csvNoName':'No se encontró ninguna fila con nombre','toast.uploading':'Subiendo','toast.update':'🚀 Hay una versión nueva disponible.','toast.updateBtn':'Actualizar',
    'cob.allCollected':'Todo cobrado','cob.nonePending':'No tienes pedidos pendientes de cobro.','cob.urgent':'URGENTE','cob.collect':'✅ Cobrar','cob.ref':'Ref:',
    'cob.toCollectLbl':'Por cobrar','cob.urgent7':'Urgentes (+7 días)','cob.inProgress':'En curso','cob.secUrgent':'🔴 Urgentes — más de 7 días sin cobrar','cob.secInProgress':'🔵 En curso — pendiente o imprimiendo','cob.secRecent':'🟡 Terminados recientes',
    'cob.reminder':'Hola {n}, te recuerdo que el pedido "{p}" está listo para recoger/cobrar. Total: {tot}. ¡Gracias!',
    'cfg.title':'Configuración','cfg.costParams':'⚙️ Parámetros de coste','cfg.costPerGram':'Coste por gramo por defecto (€/g)','cfg.kwh':'Precio kWh electricidad (€/kWh)','cfg.margin':'Margen de beneficio (%)','cfg.currency':'Moneda','cfg.taxName':'Nombre del impuesto','cfg.taxRate':'Tipo impositivo (%)','cfg.taxHint':'0% = sin impuesto en facturas. El impuesto se añade encima del precio al generar la factura.','cfg.saveConfig':'Guardar configuración',
    'cfg.bizData':'🏢 Datos de empresa','cfg.bizHint':'Aparecen en PDFs, facturas y en la barra superior. Si dejas el nombre vacío y no subes logo, se mantiene el branding B3D Print Studio por defecto.','cfg.bizName':'Nombre de empresa','cfg.bizNif':'NIF / CIF empresa','cfg.bizAddress':'Dirección','cfg.bizPhone':'Teléfono (Bizum)','cfg.bizEmail':'Email de contacto','cfg.logoLabel':'Logo para PDFs (opcional)','cfg.noLogo':'Sin logo','cfg.removeLogo':'🗑️ Quitar logo','cfg.logoHint':'PNG, JPG, WebP o SVG. Máx 300 KB. Cuadrado o casi cuadrado funciona mejor.','cfg.saveBiz':'Guardar datos empresa',
    'cfg.intlFormat':'🌍 Formato internacional','cfg.intlHint':'Configura el formato de fechas, decimales y numeración para adaptarte a cualquier país.','cfg.dateFormat':'Formato de fecha','cfg.decimalSep':'Separador decimal','cfg.docNumbering':'Numeración de documentos','cfg.quotePrefix':'Prefijo presupuestos','cfg.invoicePrefix':'Prefijo facturas','cfg.resultLabel':'Resultado:','cfg.secondTax':'Segundo impuesto (opcional)','cfg.secondTaxHint':'Canadá (GST+PST), EEUU (State+Local tax), etc. Aparece como línea adicional en la factura.','cfg.secondTaxName':'Nombre segundo impuesto','cfg.secondTaxRate':'Tipo segundo impuesto (%)','cfg.saveFormat':'Guardar formato',
    'cfg.myAccount':'👤 Mi cuenta','cfg.emailLabel':'Email:','cfg.cloudNote':'☁️ Datos guardados en Supabase.<br>Accede desde cualquier dispositivo.','cfg.backup':'💾 Copia de seguridad','cfg.backupHint':'Descarga un JSON con todos tus datos (clientes, pedidos, impresoras, filamentos, piezas, gastos y configuración). Las imágenes y ficheros subidos no se incluyen, solo su referencia.','cfg.downloadBackup':'⬇️ Descargar copia (JSON)','cfg.restoreBackup':'♻️ Restaurar copia',
    'cfg.notifs':'🔔 Notificaciones','cfg.notifsHint':'Recibe avisos cuando un filamento esté bajo, haya pedidos sin cobrar o una impresora necesite mantenimiento.','cfg.notifNotSupported':'❌ No soportado en este navegador','cfg.notifActive':'✅ Notificaciones activas','cfg.notifBlocked':'⛔ Bloqueadas — actívalas en ajustes del navegador','cfg.notifNotSet':'Sin configurar','cfg.notifCheck':'🔔 Comprobar alertas ahora','cfg.notifEnable':'🔔 Activar notificaciones',
    'cfg.priceFormula':'💡 Fórmula de precios','cfg.fMatCost':'Coste material','cfg.fElecCost':'Coste eléctrico','cfg.fTotalCost':'Coste total','cfg.fWithProfit':'Con ganancia manual:','cfg.fWithMargin':'Con margen:','cfg.cfgSaved':'Configuración guardada','cfg.bizSaved':'Datos de empresa guardados','cfg.formatSaved':'Formato guardado',
    'pdf.quote':'PRESUPUESTO','pdf.invoice':'FACTURA','pdf.no':'Nº:','pdf.project':'Proyecto:','pdf.date':'Fecha:','pdf.quoteRef':'Presupuesto ref.:','pdf.client':'CLIENTE','pdf.billTo':'FACTURAR A','pdf.orderData':'DATOS DEL PEDIDO','pdf.rName':'Nombre','pdf.rNif':'NIF/CIF','pdf.rCompany':'Empresa','pdf.rPhone':'Teléfono','pdf.rEmail':'Email','pdf.colPieceFil':'PIEZA / FILAMENTO','pdf.uds':'Uds','pdf.weight':'Peso','pdf.time':'Tiempo','pdf.totalWeight':'Peso total:','pdf.totalTime':'Tiempo total:','pdf.material':'Material','pdf.notes':'Notas:','pdf.totalPrice':'PRECIO TOTAL','pdf.taxNotIncl':'no incluido','pdf.taxesNotIncl':'Impuestos no incluidos','pdf.payBizum':'FORMA DE PAGO — BIZUM','pdf.payBizumHint':'Pago por Bizum al número indicado','pdf.thanks':'¡Gracias por confiar en nosotros!','pdf.paid':'PAGADO','pdf.serviceDetail':'Detalle del servicio','pdf.colDesc':'Descripción','pdf.design':'Diseño','pdf.postproc':'Postprocesado','pdf.taxBase':'Base imponible','pdf.totalInvoiced':'TOTAL FACTURADO','pdf.invoiceWord':'Factura','pdf.proyecto':'Proyecto','pdf.fecha':'Fecha',
    'rpt.generatedOn':'Generado el','rpt.monthly':'Informe mensual','rpt.annual':'Informe anual','rpt.income':'Ingresos','rpt.collectedN':'cobrado(s)','rpt.totalExpenses':'Gastos totales','rpt.prodPlusExp':'Producción + gastos','rpt.netProfit':'Beneficio neto','rpt.margin':'Margen:','rpt.totalOrders':'Total pedidos','rpt.pending':'Pendientes','rpt.printing':'Imprimiendo',
    'rpt.ordersOfMonth':'Pedidos del mes','rpt.expensesOfMonth':'Gastos del mes','rpt.filamentUse':'Consumo de filamento (pedidos cobrados)','rpt.costBreakdown':'Desglose de costes de producción','rpt.topClients':'Top clientes del mes',
    'rpt.cClient':'Cliente','rpt.cDate':'Fecha','rpt.cPrice':'Precio','rpt.cStatus':'Estado','rpt.cDesc':'Descripción','rpt.cCategory':'Categoría','rpt.cSupplier':'Proveedor','rpt.cAmount':'Importe','rpt.cMaterial':'Material','rpt.cUsed':'Consumido','rpt.cConcept':'Concepto','rpt.cCost':'Coste','rpt.cPctTotal':'% del total','rpt.cBilled':'Facturado','rpt.cPctIncome':'% ingresos',
    'rpt.noOrdersMonth':'Sin pedidos este mes','rpt.noExpensesMonth':'Sin gastos este mes','rpt.noFilament':'Sin consumo registrado','rpt.noPaidOrders':'Sin pedidos cobrados',
    'rpt.totalExpensesFoot':'Total gastos','rpt.totalProdCost':'Total costes producción','rpt.bMaterial':'Material','rpt.bElectricity':'Electricidad','rpt.bDesign':'Diseño','rpt.bPostproc':'Postprocesado',
    'rpt.annualSummary':'Resumen completo','rpt.ordersWord':'pedidos','rpt.collectedWord':'cobrados','rpt.totalIncome':'Ingresos totales','rpt.paidOrders':'pedidos cobrados','rpt.monthlyAvg':'Media mensual','rpt.ordersPerMonth':'pedidos/mes','rpt.bestMonth':'Mejor mes','rpt.worstMonth':'Mes más flojo','rpt.monthlyBreakdown':'Desglose mensual','rpt.cMonth':'Mes','rpt.cProdCosts':'Costes prod.','rpt.cExpenses':'Gastos','rpt.cProfit':'Beneficio','rpt.cOrders':'Pedidos','rpt.total':'TOTAL','rpt.exportMonthly':'Exportar informe mensual','rpt.pickMonth':'Selecciona el mes y año para generar el informe en PDF.','rpt.month':'Mes','rpt.year':'Año','rpt.genPdf':'📊 Generar PDF','rpt.annualDesc':'Resumen completo del año con desglose mensual.','rpt.genPdfAnnual':'📈 Generar PDF'
  },
  en: {
    'nav.dashboard':'Dashboard','nav.agenda':'Schedule','nav.clientes':'Customers',
    'agenda.title':'Schedule','agenda.overdue':'Overdue','agenda.todayTitle':'For today','agenda.today':'Today','agenda.week':'This week','agenda.noDate':'No delivery date','agenda.empty':'No pending deliveries. All caught up! 🎉','agenda.late':'{n} day(s) ago','agenda.in':'in {n} day(s)','agenda.toCollect':'Pending payment','agenda.later':'Later','agenda.deliver':'Mark delivered','agenda.collect':'Collect','nav.pedidos':'Orders','nav.impresoras':'Printers',
    'nav.filamentos':'Filaments','nav.piezas':'Parts','nav.cobros':'Payments','nav.archivos':'Files',
    'nav.gastos':'Expenses','nav.registro':'Tax record','nav.calculadora':'Calculator','nav.configuracion':'Settings','nav.admin':'Admin',
    'nav.grp.ventas':'Sales','nav.grp.taller':'Workshop','nav.grp.finanzas':'Finance',
    'common.logout':'Sign out','common.menu':'Menu','common.cancel':'Cancel','common.save':'Save','common.new':'+ New','common.delete':'Delete',
    'common.day':'day','common.days':'days','common.prev':'← Previous','common.next':'Next →',
    'topbar.searchDesk':'Search customers, orders, parts…','net.offline':'Offline','net.unsynced':'unsynced',
    'theme.toggle':'Toggle theme','lang.toggle':'Change language (ES/EN)',
    'col.num':'No.','col.project':'Project','col.material':'Material','col.price':'Price','col.status':'Status','col.date':'Date',
    'dash.title':'Dashboard','dash.subtitle':'Your business at a glance','dash.monthlyReport':'Monthly report','dash.annualReport':'Annual report',
    'dash.incomeCollected':'Income collected','dash.paidOrders':'paid orders','dash.prodCosts':'Production costs',
    'dash.totalExpenses':'Total expenses','dash.expenses':'expenses','dash.netProfit':'Net profit','dash.marginOk':'Positive margin ✓','dash.checkPrices':'Review pricing',
    'dash.totalOrders':'Total orders','dash.pending':'pending','dash.printing':'printing',
    'dash.incomeByMonth':'Income by month','dash.byStatus':'By status','dash.tapToFilter':'— tap to filter','dash.topMaterials':'Most used materials',
    'dash.recentOrders':'Recent orders','dash.noOrdersYet':'No orders yet','dash.noOrders':'No orders',
    'dash.lowFilament':'Low filament stock','dash.gLeft':'g left','dash.restock':'Restock',
    'dash.pendingCollect':'Pending payment','dash.finishedUnpaid':'unpaid orders','dash.collect':'Collect',
    'dash.staleOrders':'Stale orders','dash.staleSub':'Same status for 3+ days','dash.update':'Update',
    'an.title':'Analytics','an.avgTicket':'Average ticket','an.avgTicketSub':'per paid order','an.conversion':'Conversion rate','an.conversionSub':'quotes paid','an.grossProfit':'Gross profit','an.grossMargin':'margin','an.profitByClient':'Profit by customer','an.profitByMaterial':'Profit by material','an.colProfit':'Profit','an.colIncome':'Income','an.colOrders':'Orders','an.colMargin':'Margin','an.noData':'No paid orders yet','an.client':'Customer','an.material':'Material',
    'st.todos':'all','st.pendiente':'pending','st.imprimiendo':'printing','st.terminado':'finished','st.entregado':'delivered','st.cobrado':'paid','st.pagado':'paid','st.activa':'active','st.mantenimiento':'maintenance','st.averiada':'broken',
    'common.exportExcel':'Export Excel','common.page':'Page','common.of':'of','common.search':'Search…',
    'ped.title':'Orders','ped.ordersWord':'orders','ped.inTotal':'total','ped.searchProject':'Search project, client, invoice no.…',
    'ped.selectedWord':'selected','ped.changeStatusTo':'→ Change status to:','ped.deselect':'✕ Deselect',
    'ped.empty':'No orders — create your first one 👆','ped.selectAll':'Select page','ped.deselectAll':'Deselect all',
    'col.client':'Customer','col.weight':'Weight','col.numInvoice':'No. / Invoice',
    'ped.tPresupuesto':'Quote PDF','ped.tWhatsApp':'WhatsApp','ped.tCobrado':'Mark as paid','ped.tYaCobrado':'Already paid',
    'ped.tVerFactura':'View invoice PDF','ped.tGenFactura':'Create invoice','ped.tEnviarFactura':'Send invoice via WhatsApp',
    'ped.tDuplicar':'Duplicate order','ped.tSoloPagados':'Paid orders only','ped.types':'types','ped.units':'units',
    'ped.overdue':'overdue','ped.delivery':'delivery','ped.paidBadge':'paid','ped.deposit':'Deposit','ped.balance':'balance',
    'share.title':'Share quote','share.linkReady':'Acceptance link ready. Copy it or send it to the client — they can view and accept it online:','share.copy':'📋 Copy link','share.copied':'Link copied','share.openWa':'💬 Send via WhatsApp','share.waMsg':'Hi! Here is your quote for "{p}". You can view and accept it here: {url}','share.needSql':'Feature not available yet: run migration sql/010 in Supabase.','share.accepted':'Accepted','share.tShare':'Share acceptance link',
    'plan.limitTitle':'Plan limit reached','plan.proMonthly':'💳 Pro Monthly — €9/mo','plan.proAnnual':'💳 Pro Annual — €79/yr','plan.payPaypal':'Pay with PayPal','plan.notNow':'Not now','plan.redirecting':'Opening secure checkout…','plan.checkoutErr':'Could not start checkout','plan.thanks':'✅ Payment received! Activating your Pro plan…',
    'email.title':'Send by email','email.recipient':'Recipient email:','email.testNote':'The email will be sent from your domain (brami3d.app) with your business name; replies go to your contact email.','email.send':'Send','email.invalidTo':'Enter a valid email','email.sent':'✅ Email sent','email.errPrefix':'Could not send','email.hi':'Hi','email.regards':'Best regards,','email.subjQuote':'Quote {n}','email.subjInvoice':'Invoice {n}','email.quoteIntro':'Here is the quote for "{p}".','email.invoiceIntro':'Attached is invoice {n} for "{p}".','email.priceLine':'Total price: {v}.','email.totalLine':'Total: {v}.','email.subjReminder':'Reminder — Quote {n}','email.reminderIntro':'I sent you the quote for "{p}" a few days ago and did not want it to slip by. Attached again.','email.reminderLink':'You can view and accept it online here: {url}','ped.tRecordar':'Remind client about this quote',
    'frm.editOrder':'Edit order','frm.newOrder':'New order','frm.saveOrder':'💾 Save order','frm.noClient':'No customer',
    'frm.projectName':'Project name *','frm.orderDate':'Order date','frm.deliveryDate':'Delivery date (optional)',
    'frm.printer':'Printer','frm.noPrinter':'No printer (200W default)',
    'frm.designCost':'Design cost (€)','frm.postCost':'Post-processing cost (€)',
    'frm.manualProfit':'Manual profit (€) — empty = auto margin','frm.salePrice':'Sale price (€) — overrides all (0 = free / loss)',
    'frm.deposit':'Deposit / advance paid (€)','frm.orderPaid':'💰 Order paid','frm.markPaid':'💰 Mark as paid',
    'frm.paidOn':'Paid on {d}','frm.willInvoice':'Marking as paid will create the invoice','frm.notes':'Notes',
    'frm.refPhoto':'📷 Reference photo','frm.addPhoto':'Add reference photo','frm.photoHint':'JPG, PNG, WebP — max 10MB',
    'frm.orderParts':'Order parts','frm.partsHint':'Each part is printed separately.','frm.addPart':'+ Add part',
    'frm.totalWeight':'Total weight','frm.totalTime':'Total time','frm.parts':'Parts','frm.costPreview':'Cost preview',
    'ln.noTemplate':'── No template ──','ln.manual':'── Manual ──','ln.weightG':'Weight (g):','ln.part':'Part','ln.remove':'✕ Remove',
    'ln.template':'Template','ln.descRequired':'Description *','ln.descPlaceholder':'e.g. Side bracket','ln.qty':'Quantity','ln.unitTime':'Unit time (h)',
    'ln.filaments':'🧵 Filaments for this part','ln.addFilament':'+ Add filament','ln.partWeight':'Part total weight:',
    'cp.filamentCost':'Filament cost','cp.electricity':'Electricity','cp.postproc':'Post-processing','cp.design':'Design','cp.totalCost':'Total cost','cp.profit':'Profit','cp.finalPrice':'FINAL PRICE',
    'save.projectRequired':'Project is required','save.addPart':'Add at least one part','save.saved':'✅ Order saved','save.savedOk':'Order saved successfully',
    'save.sendQuoteTo':'Send the quote to','save.sendWhatsApp':'💬 Send via WhatsApp','save.notNow':'Not now','save.bulkUpdated':'orders updated to',
    'col.name':'Name','col.empresa':'Company','col.phone':'Phone','col.email':'Email','col.notes':'Notes','col.nif':'Tax ID',
    'cli.title':'Customers','cli.clientsWord':'customers','cli.empty':'No customers','cli.purchaseHistory':'📋 Purchase history','cli.tHistory':'History',
    'cli.editClient':'Edit customer','cli.newClient':'New customer','cli.nameRequired':'Name *','cli.address':'Address',
    'cli.saved':'Customer saved','cli.nameReq':'Name is required','cli.deleteConfirm':'Delete this customer?','cli.importCsv':'📥 Import CSV',
    'common.close':'Close','hist.noOrders':'No orders yet','hist.orders':'Orders','hist.paid':'Paid','hist.totalCollected':'Total collected',
    'common.edit':'Edit','common.saved':'Saved','common.deleted':'Deleted','common.nameReq':'Name is required',
    'a11y.delete':'Delete','a11y.remove':'Remove','a11y.search':'Search','a11y.lang':'Switch language','a11y.theme':'Toggle theme',
    'onb.title':'Welcome to Brami3D! 👋','onb.intro':'Three steps and your workshop is ready to go.','onb.doneTag':'✓ Done','onb.skip':'Explore on my own',
    'onb.s1t':'Set up your business','onb.s1d':'Name, logo and taxes for your invoices.','onb.s1b':'Set up',
    'onb.s2t':'Add your first filament','onb.s2d':'Log a spool with its price and stock.','onb.s2b':'Add filament',
    'onb.s3t':'Create your first order','onb.s3d':'Calculate the price and generate the quote or invoice.','onb.s3b':'Create order',
    'err.generic':'Something went wrong. Please try again.',
    'trial.daysLeft':'You have {n} days left in your free trial.','trial.lastDay':'Today is the last day of your free trial.','trial.upgrade':'Upgrade to Pro',
    'cfg.notifTest':'📲 Send a test notification','push.testBody':'It works! Your notifications are on.','push.testSent':'✅ Notification sent — check your device','push.testNone':'No subscribed devices yet',
    'cfg.dangerZone':'Danger zone','cfg.deleteAccount':'Delete my account','cfg.deleteAccountHint':'Permanently delete your account and all your data (orders, customers, invoices…). This cannot be undone.',
    'del.title':'Delete account','del.warn':'This will permanently delete your account and ALL your data: orders, customers, filaments, invoices and settings. This cannot be undone.','del.confirmHint':'To confirm, type DELETE:','del.confirmWord':'DELETE','del.confirmBtn':'Delete everything','del.done':'Your account and data have been deleted.','del.error':'Could not delete the account',
    'help.btn':'Help','help.title':'Help & contact','help.intro':'Quick answers — and if not, message us, we reply within 24h.',
    'help.q1':'How do I create an invoice?','help.a1':'Mark the order as paid and the legal invoice is generated automatically. View or share it as PDF from the order itself.',
    'help.q2':'How do I upgrade to Pro?','help.a2':'Tap your plan at the top (the badge next to your name) and pick Pro monthly or annual. Paying by card activates it instantly.',
    'help.q3':'Is my data safe?','help.a3':'Yes. It is stored encrypted in the cloud and only you can access it. You can export it or delete your account anytime.',
    'help.wa':'Message us on WhatsApp','help.email':'Send us an email','help.waMsg':'Hi, I need help with Brami3D',
    'cfg.referrals':'🤝 Refer & earn','cfg.referralsHint':'Invite another workshop. When they sign up with your link, you both get 30 days of Pro free.','cfg.referralsBtn':'See my invite link',
    'ref.title':'Refer & earn','ref.intro':'Share your link. When another workshop signs up with it, you both get 30 days of Pro free. 🎁','ref.copy':'Copy','ref.copied':'Link copied','ref.share':'Share on WhatsApp','ref.count':'Workshops you have invited','ref.waMsg':'I recommend Brami3D to manage your 3D printing workshop. Sign up with my link and we both get 30 days of Pro free: {url}','ref.rewarded':'🎁 Welcome! You have 30 days of Pro free for joining via an invite.',
    'imp.title':'Printers','imp.new':'+ New printer','imp.empty':'No printers','imp.wear':'Wear','imp.needsReview':'needs servicing','imp.elecCost':'Electricity cost','imp.regUse':'⏱ Log usage','imp.editTitle':'Edit printer','imp.newTitle':'New printer','imp.fModel':'Model','imp.fHours':'Hours of use','imp.fWear':'% Wear','imp.fConsumo':'Power draw (W)','imp.consumoHint':'Enter your printer wattage','imp.delete':'Delete this printer?','imp.logUsage':'⏱ Log usage','imp.accNow':'Current total:','imp.wearWord':'Wear:','imp.estElecCost':'Est. electricity cost:','imp.sessHours':'Hours this session *','imp.extraWear':'Extra wear (%)','imp.wearAuto':'If wear is left at 0, +0.1% per hour is applied automatically.','imp.fMantCada':'Maintenance every (h)','imp.maint':'Maintenance','imp.maintDue':'Maintenance due','imp.mantBtn':'Maintenance done','imp.mantDone':'Maintenance logged ✅',
    'fil.title':'Filaments','fil.empty':'No filaments','fil.cRemaining':'Remaining','fil.cStock':'Stock','fil.editTitle':'Edit filament','fil.newTitle':'New filament','fil.fType':'Type','fil.fBrand':'Brand *','fil.fColor':'Color','fil.fRemaining':'Remaining weight (g)','fil.fPriceKg':'Price per kg (€)','fil.brandReq':'Brand is required','fil.delete':'Delete this filament?','fil.cType':'Type','fil.cBrand':'Brand','fil.cColor':'Color',
    'pz.title':'Parts','pz.new':'+ New part','pz.empty':'No saved parts','pz.hint':'Save frequent parts to auto-fill orders.','pz.material':'Material','pz.weight':'Weight','pz.time':'Time','pz.suggested':'Suggested','pz.editTitle':'Edit part','pz.newTitle':'New part','pz.fName':'Name *','pz.fMaterial':'Material','pz.fWeight':'Weight (g)','pz.fTime':'Print time (h)','pz.fSuggested':'Suggested price (€)','pz.delete':'Delete this part?',
    'gas.title':'Expenses','gas.subtitle':'Track all your expenses','gas.new':'+ New expense','gas.empty':'No expenses recorded','gas.total':'Total expenses','gas.registered':'expenses recorded','gas.thisMonth':'This month','gas.byCat':'By category','gas.noData':'No data','gas.editTitle':'Edit expense','gas.newTitle':'New expense','gas.fDesc':'Description *','gas.fCat':'Category','gas.fAmount':'Amount (€)','gas.fDate':'Date','gas.fSupplier':'Supplier','gas.descReq':'Description is required','gas.saved':'Expense saved','gas.delete':'Delete this expense?',
    'arch.title':'Files','arch.hint':'STL and images — stored in Supabase Storage (max 50MB).','arch.drop':'Drag files or click','arch.dropHint':'STL · JPG · PNG · WebP · GIF · SVG · Max 50MB','arch.empty':'No files',
    'cob.title':'Pending payments','cob.toCollect':'to collect','calc.title':'🧮 Quick calculator','calc.subtitle':'Estimate cost and price without creating an order','calc.printParams':'Print parameters','calc.filament':'Filament','calc.filManual':'── Manual cost (€/kg) ──','calc.filCost':'Filament cost (€/kg)','calc.weightG':'Weight (g)','calc.printTime':'Print time (h)','calc.printer':'Printer','calc.noPrinter':'── No printer (200W) ──','calc.postproc':'Post-processing','calc.design':'Design / modeling','calc.margin':'Profit margin (%)','calc.manualPrice':'Manual final price','calc.manualPriceHint':'— leave empty to calculate automatically','calc.optional':'Optional','calc.enterData':'Enter data to see the breakdown','calc.breakdown':'Cost breakdown','calc.cMaterial':'Material','calc.cElectricity':'Electricity','calc.cPostproc':'Post-processing','calc.cDesign':'Design','calc.cTotalCost':'Total cost','calc.manualPriceLbl':'Manual price','calc.suggestedPrice':'Suggested price','calc.marginWord':'margin','calc.profit':'Profit','calc.priceByMargin':'Price table by margin','calc.colMargin':'Margin','calc.colPrice':'Price','calc.colProfit':'Profit',
    'toast.connRestored':'✅ Connection restored','toast.offline':'⚠️ Offline — offline mode','toast.notifNotSupported':'Your browser does not support notifications','toast.notifOn':'Notifications enabled','toast.permDenied':'Permission denied','toast.photoTooBig':'Photo exceeds 10MB','toast.logoFormat':'Invalid format. Use PNG, JPG, WebP or SVG.','toast.notesSaved':'Notes saved','toast.planUpdated':'Plan updated','toast.csvInvalid':'Invalid CSV','toast.csvEmpty':'CSV is empty','toast.csvNoName':'No row with a name found','toast.uploading':'Uploading','toast.update':'🚀 A new version is available.','toast.updateBtn':'Update',
    'cob.allCollected':'All collected','cob.nonePending':'You have no pending payments.','cob.urgent':'URGENT','cob.collect':'✅ Collect','cob.ref':'Ref:',
    'cob.toCollectLbl':'To collect','cob.urgent7':'Urgent (+7 days)','cob.inProgress':'In progress','cob.secUrgent':'🔴 Urgent — unpaid for over 7 days','cob.secInProgress':'🔵 In progress — pending or printing','cob.secRecent':'🟡 Recently finished',
    'cob.reminder':'Hi {n}, a reminder that your order "{p}" is ready for pickup/payment. Total: {tot}. Thank you!',
    'cfg.title':'Settings','cfg.costParams':'⚙️ Cost parameters','cfg.costPerGram':'Default cost per gram (€/g)','cfg.kwh':'Electricity price per kWh (€/kWh)','cfg.margin':'Profit margin (%)','cfg.currency':'Currency','cfg.taxName':'Tax name','cfg.taxRate':'Tax rate (%)','cfg.taxHint':'0% = no tax on invoices. Tax is added on top of the price when generating the invoice.','cfg.saveConfig':'Save settings',
    'cfg.bizData':'🏢 Business details','cfg.bizHint':'They appear on PDFs, invoices and the top bar. If you leave the name empty and upload no logo, the default B3D Print Studio branding is kept.','cfg.bizName':'Business name','cfg.bizNif':'Business tax ID','cfg.bizAddress':'Address','cfg.bizPhone':'Phone (Bizum)','cfg.bizEmail':'Contact email','cfg.logoLabel':'Logo for PDFs (optional)','cfg.noLogo':'No logo','cfg.removeLogo':'🗑️ Remove logo','cfg.logoHint':'PNG, JPG, WebP or SVG. Max 300 KB. Square or near-square works best.','cfg.saveBiz':'Save business details',
    'cfg.intlFormat':'🌍 International format','cfg.intlHint':'Set date, decimal and numbering formats to suit any country.','cfg.dateFormat':'Date format','cfg.decimalSep':'Decimal separator','cfg.docNumbering':'Document numbering','cfg.quotePrefix':'Quote prefix','cfg.invoicePrefix':'Invoice prefix','cfg.resultLabel':'Result:','cfg.secondTax':'Second tax (optional)','cfg.secondTaxHint':'Canada (GST+PST), US (State+Local tax), etc. Appears as an extra line on the invoice.','cfg.secondTaxName':'Second tax name','cfg.secondTaxRate':'Second tax rate (%)','cfg.saveFormat':'Save format',
    'cfg.myAccount':'👤 My account','cfg.emailLabel':'Email:','cfg.cloudNote':'☁️ Data stored in Supabase.<br>Access from any device.','cfg.backup':'💾 Backup','cfg.backupHint':'Download a JSON with all your data (customers, orders, printers, filaments, parts, expenses and settings). Uploaded images/files are not included, only their reference.','cfg.downloadBackup':'⬇️ Download backup (JSON)','cfg.restoreBackup':'♻️ Restore backup',
    'cfg.notifs':'🔔 Notifications','cfg.notifsHint':'Get alerts when filament is low, orders are unpaid, or a printer needs servicing.','cfg.notifNotSupported':'❌ Not supported in this browser','cfg.notifActive':'✅ Notifications active','cfg.notifBlocked':'⛔ Blocked — enable them in your browser settings','cfg.notifNotSet':'Not set up','cfg.notifCheck':'🔔 Check alerts now','cfg.notifEnable':'🔔 Enable notifications',
    'cfg.priceFormula':'💡 Pricing formula','cfg.fMatCost':'Material cost','cfg.fElecCost':'Electricity cost','cfg.fTotalCost':'Total cost','cfg.fWithProfit':'With manual profit:','cfg.fWithMargin':'With margin:','cfg.cfgSaved':'Settings saved','cfg.bizSaved':'Business details saved','cfg.formatSaved':'Format saved',
    'pdf.quote':'QUOTE','pdf.invoice':'INVOICE','pdf.no':'No.:','pdf.project':'Project:','pdf.date':'Date:','pdf.quoteRef':'Quote ref.:','pdf.client':'CUSTOMER','pdf.billTo':'BILL TO','pdf.orderData':'ORDER DETAILS','pdf.rName':'Name','pdf.rNif':'Tax ID','pdf.rCompany':'Company','pdf.rPhone':'Phone','pdf.rEmail':'Email','pdf.colPieceFil':'PART / FILAMENT','pdf.uds':'Qty','pdf.weight':'Weight','pdf.time':'Time','pdf.totalWeight':'Total weight:','pdf.totalTime':'Total time:','pdf.material':'Material','pdf.notes':'Notes:','pdf.totalPrice':'TOTAL PRICE','pdf.taxNotIncl':'not included','pdf.taxesNotIncl':'Taxes not included','pdf.payBizum':'PAYMENT — BIZUM','pdf.payBizumHint':'Pay by Bizum to the number shown','pdf.thanks':'Thank you for your trust!','pdf.paid':'PAID','pdf.serviceDetail':'Service details','pdf.colDesc':'Description','pdf.design':'Design','pdf.postproc':'Post-processing','pdf.taxBase':'Tax base','pdf.totalInvoiced':'TOTAL INVOICED','pdf.invoiceWord':'Invoice','pdf.proyecto':'Project','pdf.fecha':'Date',
    'rpt.generatedOn':'Generated on','rpt.monthly':'Monthly report','rpt.annual':'Annual report','rpt.income':'Income','rpt.collectedN':'collected','rpt.totalExpenses':'Total expenses','rpt.prodPlusExp':'Production + expenses','rpt.netProfit':'Net profit','rpt.margin':'Margin:','rpt.totalOrders':'Total orders','rpt.pending':'Pending','rpt.printing':'Printing',
    'rpt.ordersOfMonth':'Orders this month','rpt.expensesOfMonth':'Expenses this month','rpt.filamentUse':'Filament usage (paid orders)','rpt.costBreakdown':'Production cost breakdown','rpt.topClients':'Top customers this month',
    'rpt.cClient':'Customer','rpt.cDate':'Date','rpt.cPrice':'Price','rpt.cStatus':'Status','rpt.cDesc':'Description','rpt.cCategory':'Category','rpt.cSupplier':'Supplier','rpt.cAmount':'Amount','rpt.cMaterial':'Material','rpt.cUsed':'Used','rpt.cConcept':'Concept','rpt.cCost':'Cost','rpt.cPctTotal':'% of total','rpt.cBilled':'Billed','rpt.cPctIncome':'% income',
    'rpt.noOrdersMonth':'No orders this month','rpt.noExpensesMonth':'No expenses this month','rpt.noFilament':'No usage recorded','rpt.noPaidOrders':'No paid orders',
    'rpt.totalExpensesFoot':'Total expenses','rpt.totalProdCost':'Total production cost','rpt.bMaterial':'Material','rpt.bElectricity':'Electricity','rpt.bDesign':'Design','rpt.bPostproc':'Post-processing',
    'rpt.annualSummary':'Full summary','rpt.ordersWord':'orders','rpt.collectedWord':'collected','rpt.totalIncome':'Total income','rpt.paidOrders':'paid orders','rpt.monthlyAvg':'Monthly average','rpt.ordersPerMonth':'orders/month','rpt.bestMonth':'Best month','rpt.worstMonth':'Slowest month','rpt.monthlyBreakdown':'Monthly breakdown','rpt.cMonth':'Month','rpt.cProdCosts':'Prod. costs','rpt.cExpenses':'Expenses','rpt.cProfit':'Profit','rpt.cOrders':'Orders','rpt.total':'TOTAL','rpt.exportMonthly':'Export monthly report','rpt.pickMonth':'Pick the month and year to generate the PDF report.','rpt.month':'Month','rpt.year':'Year','rpt.genPdf':'📊 Generate PDF','rpt.annualDesc':'Full-year summary with monthly breakdown.','rpt.genPdfAnnual':'📈 Generate PDF'
  }
};
function t(key, vars){
  let s = (I18N[LANG] && I18N[LANG][key]) || (I18N.es && I18N.es[key]) || key;
  if(vars) for(const k in vars) s = s.replace(new RegExp('\\{'+k+'\\}','g'), vars[k]);
  return s;
}
// Banderas en SVG (los emojis 🇬🇧/🇪🇸 NO se renderizan en Windows).
const FLAG_GB = '<svg viewBox="0 0 60 30" width="22" height="14" style="display:block;border-radius:3px"><clipPath id="fgb1"><path d="M0,0 v30 h60 v-30 z"/></clipPath><clipPath id="fgb2"><path d="M30,15 h30 v15 z v15 h-30 z h-30 v-15 z v-15 h30 z"/></clipPath><g clip-path="url(#fgb1)"><path d="M0,0 v30 h60 v-30 z" fill="#012169"/><path d="M0,0 L60,30 M60,0 L0,30" stroke="#fff" stroke-width="6"/><path d="M0,0 L60,30 M60,0 L0,30" clip-path="url(#fgb2)" stroke="#C8102E" stroke-width="4"/><path d="M30,0 v30 M0,15 h60" stroke="#fff" stroke-width="10"/><path d="M30,0 v30 M0,15 h60" stroke="#C8102E" stroke-width="6"/></g></svg>';
const FLAG_ES = '<svg viewBox="0 0 3 2" width="22" height="14" style="display:block;border-radius:3px"><rect width="3" height="2" fill="#c60b1e"/><rect width="3" height="1" y="0.5" fill="#ffc400"/></svg>';

// Aplica traducciones a los elementos estáticos del HTML (los que no pasan por render()).
function applyStaticI18n(){
  document.documentElement.lang = LANG;
  const set=(id,txt)=>{ const e=$(id); if(e) e.textContent=txt; };
  set('logout-lbl', t('common.logout'));
  const gs=$('global-search'); if(gs) gs.placeholder=t('topbar.searchDesk');
  const nl=$('net-label'); if(nl && !_outboxCount()) nl.textContent=t('net.offline');
  const lb=$('lang-btn'); if(lb){ lb.innerHTML = LANG==='es'?FLAG_GB:FLAG_ES; lb.title = LANG==='es'?'Switch to English':'Cambiar a español'; lb.setAttribute('aria-label', lb.title); }
  const tb=$('theme-btn'); if(tb){ tb.title=t('theme.toggle'); tb.setAttribute('aria-label', t('a11y.theme')); }
  const msb=$('mob-search-btn'); if(msb) msb.setAttribute('aria-label', t('a11y.search'));
  const hb=$('help-btn'); if(hb){ hb.title=t('help.btn'); hb.setAttribute('aria-label', t('help.btn')); }
}
function setLang(l){
  LANG = (l==='en')?'en':'es';
  try{ localStorage.setItem('b3d_lang', LANG); }catch(_){}
  applyStaticI18n();
  try{ buildNav(); }catch(_){}
  try{ refreshBizHeader(); }catch(_){}
  try{ render(); }catch(_){}
  try{ _updatePendingBadge(); }catch(_){}
}
function toggleLang(){ setLang(LANG==='es'?'en':'es'); }
